- name: First Play
  hosts: localhost
  become: yes
#  become_user: root
#  vars:
#    var1: value
#  vars_files:
#    - var-file.txt
  tasks:
    - name: setup dependencies
      apt:
        update_cache: yes
        name:
          - wget
          - supervisor
          - python
          - python3-pip

#    - name: pip setup part
#      pip:
#      extra_args: --upgrade
#        name:
#          - pip
#          - virtualenv

    - name: pip setup part7
      pip:
        name:
          - pip
          - virtualenv
        extra_args: --upgrade
#  handlers:
#  - name: some_name
#    service: name=service_name state=running or restarted
