- name: First Play
  hosts: localhost
  become: yes
  become_user: root
#  vars:
#    var1: value
#  vars_files:
#    - var-file.txt
  tasks:
    - name: setup dependencies
      apt:
        update_cache: yes
        name:
          - wget
          - supervisor
          - python
          - python3-pip
          - python3-pymysql

    - name: pip setup part
      pip:
        name:
          - pip
          - virtualenv
        extra_args: --upgrade

    - name: Add the user 'pythonapp' for app
      user:
        name: pythonapp
        home: /home/pythonapp
        state: present

    - name: export variable
      shell: "export HOME=/root"

    - name: clone the project
      git:
        repo: https://github.com/GoogleCloudPlatform/getting-started-python.git
        dest: /opt/app
        clone: yes
        accept_hostkey: yes

    - name: Put supervisor configuration in proper place
      copy:
        src: /opt/app/gce/python-app.conf
        dest: /etc/supervisor/conf.d/python-app.conf

    - name: Put Systemd config for mysql-proxy
      copy:
        src: /opt/playbooks/cloud-sql-proxy.service
        dest: /etc/systemd/system/cloud-sql-proxy.service

    - name: get cloud_sql_proxy executable
      get_url:
        url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
        dest: /usr/local/bin/cloud_sql_proxy

    - name: make cloud_sql_proxy executable
      file:
        path: /usr/local/bin/cloud_sql_proxy
        mode: +x

    - name: reload systemd and start cloud-sql-proxy
      systemd:
        daemon_reload: yes
        name: cloud-sql-proxy
        enabled: yes
        state: started


    - name: execute script to fast-forward
      shell: |
        pip3 install Flask Flask-SQLAlchemy
        cp -r /opt/playbooks/7-gce/* /opt/app/
        # Python environment setup
        virtualenv -p python3 /opt/app/gce/env
        source /opt/app/gce/env/bin/activate
        /opt/app/gce/env/bin/pip install -r /opt/app/gce/requirements.txt

    - name: Set ownership to newly created account
      file:
        path: /opt/app
        owner: pythonapp
        group: pythonapp
        recurse: yes

    - name: execute script to fast-forward
      shell: |
        python3 /opt/app/bookshelf/model_cloudsql.py
        # Start service via supervisorctl
        sudo supervisorctl reread
        sudo supervisorctl update

#    - name: change script permission
#      file:
#        dest=/opt/playbooks/start.sh
#        mode=+x
#
#    - name: fastforward-script
#      command: bash /opt/playbooks/start.sh


#  handlers:
#  - name: some_name
#    service: name=service_name state=running or restarted
