- name: First Play
  hosts: localhost
  become: yes
#  become_user: root
#  vars:
#    var1: value
#  vars_files:
#    - var-file.txt
  tasks:
    - name: setup dependencies
      apt:
        update_cache: yes
        name:
          - wget
          - supervisor
          - python
          - python3-pip

    - name: pip setup part
      pip:
        name:
          - pip
          - virtualenv
        extra_args: --upgrade

- name: Add the user 'pythonapp' for app
  ansible.builtin.user:
    name: pythonapp
    home: /home/pythonapp
    state: present


#  handlers:
#  - name: some_name
#    service: name=service_name state=running or restarted
